/**
 * Spoken notification lines ("The Memory Deals — your access is approved").
 *
 * The audio files are generated once by scripts/generate-voice-lines.mjs and
 * committed to public/sounds/. This module only maps a notification topic to
 * its line and plays it.
 *
 * TWO THINGS THAT SHAPE THE DESIGN:
 *
 *  1. These play only when the app is OPEN. A notification drawn by the phone
 *     with the app closed uses the phone's own sound — no website can replace
 *     it. The words are what reach a locked phone (src/lib/notify/copy.ts).
 *
 *  2. Each line is WRAPPED by the app, not by the audio file: the Memory
 *     Deals tune plays before it (see PushSoundBridge) and a short sign-off
 *     chime after it. Keeping the wrapper here rather than baked into eight
 *     MP3s means it can be retuned without regenerating any audio, and the
 *     chime stays identical to the one the rest of the app uses.
 *
 *  3. The files may not exist. They are generated by hand with an API key, so
 *     a deploy can legitimately ship without them. Every failure here is
 *     therefore silent: no console noise, no error state, and the short tune
 *     has already played regardless. A missing voice line must never be
 *     something a customer or a shopkeeper can notice as "broken".
 */

import { playBlip } from "./tune";

/** Topic key → file in public/sounds. Topics absent here have no voice line. */
const VOICE_BY_TOPIC: Record<string, string> = {
  "access.approved": "/sounds/access-approved.mp3",
  "access.expiring": "/sounds/access-expiring.mp3",
  "access.expired": "/sounds/access-expired.mp3",
  "order.placed": "/sounds/order-placed.mp3",
  "cart.reminder": "/sounds/cart-reminder.mp3",
  "admin.order.placed": "/sounds/admin-new-order.mp3",
  "admin.access.request": "/sounds/admin-new-request.mp3",
};

/** The brand sting — the slogan, for celebrations rather than alerts. */
export const BRAND_VOICE_SRC = "/sounds/brand.mp3";

/** Is there a spoken line for this topic? */
export function voiceSrcFor(topicKey: string | null | undefined): string | null {
  if (!topicKey) return null;
  return VOICE_BY_TOPIC[topicKey] ?? null;
}

/** The element currently speaking, so a second line cuts off the first. */
let current: HTMLAudioElement | null = null;

/** Stop whatever is being spoken. Safe when nothing is. */
export function stopVoice(): void {
  if (!current) return;
  try {
    current.pause();
    current.src = "";
  } catch {
    /* already gone */
  }
  current = null;
}

/**
 * Speak the line for a topic, if one exists.
 *
 * Returns true only when playback actually started. A missing file, a browser
 * that blocks autoplay, or an unsupported codec all resolve to false without
 * throwing — the caller has nothing useful to do about any of them.
 */
export function playVoice(topicKey: string | null | undefined): boolean {
  const src = voiceSrcFor(topicKey);
  if (!src || typeof window === "undefined" || typeof Audio === "undefined") {
    return false;
  }

  try {
    stopVoice();
    const audio = new Audio(src);
    audio.preload = "auto";
    // Announcements sit above the tune that just played, not under it.
    audio.volume = 1;
    // A 404 (files not generated yet) surfaces here — stay silent.
    audio.addEventListener("error", () => {
      if (current === audio) current = null;
    });
    audio.addEventListener("ended", () => {
      if (current === audio) current = null;
      // Sign-off chime, so the announcement has a clear end and does not just
      // stop dead. Silent no-op when audio is locked.
      playBlip();
    });

    current = audio;
    // Autoplay rejection is expected before the first user gesture.
    void audio.play().catch(() => {
      if (current === audio) current = null;
    });
    return true;
  } catch {
    return false;
  }
}

/** Speak the brand slogan. Used for celebrations, never for alerts. */
export function playBrandVoice(): boolean {
  if (typeof window === "undefined" || typeof Audio === "undefined") return false;
  try {
    stopVoice();
    const audio = new Audio(BRAND_VOICE_SRC);
    audio.addEventListener("error", () => {
      if (current === audio) current = null;
    });
    current = audio;
    void audio.play().catch(() => {
      if (current === audio) current = null;
    });
    return true;
  } catch {
    return false;
  }
}
