import ExcelJS from "exceljs";

/**
 * Friendly-XLSX post-processor (owner request: "make the excel sheet more
 * user friendly for bulk upload and bulk edit — editable with keyboard,
 * mouse, trackpad with super ease").
 *
 * Takes the SheetJS-generated bytes (the import template / the catalog
 * export) and re-emits them with the editing affordances SheetJS's community
 * edition cannot write:
 *
 *   - FROZEN header row (scroll anywhere, headers stay)
 *   - bold header + fill so the edit area reads instantly
 *   - AUTOFILTER on the header (sort/filter without selecting ranges)
 *   - sensible per-column widths (no squished cells to fight with)
 *   - DROPDOWN data-validations by header name — Stock status / Status /
 *     Tax inclusive become pick-lists instead of type-the-enum-exactly
 *   - wrapped text for Description
 *
 * Rules key off HEADER NAMES, so the same pass serves both workbooks; columns
 * that don't exist in a given sheet are simply skipped.
 */

/** Dropdown lists by (lowercased) header label. */
const LIST_BY_HEADER: Record<string, string[]> = {
  "stock status": ["IN_STOCK", "LOW", "OUT_OF_STOCK"],
  stockstatus: ["IN_STOCK", "LOW", "OUT_OF_STOCK"],
  status: ["ACTIVE", "INACTIVE"],
  "tax inclusive": ["true", "false"],
  tax_inclusive: ["true", "false"],
};

/** Preferred widths by (lowercased) header label; default 14. */
const WIDTH_BY_HEADER: Record<string, number> = {
  name: 42,
  description: 48,
  sku: 16,
  brand: 18,
  category: 20,
  tags: 24,
  slug: 24,
  primaryimageurl: 30,
  "variant of (parent sku)": 22,
};

/** Rows the dropdowns cover (header + this many data rows). */
const VALIDATION_ROWS = 5000;

/** Column number → A1 letter(s). */
function colLetter(n: number): string {
  let s = "";
  while (n > 0) {
    const r = (n - 1) % 26;
    s = String.fromCharCode(65 + r) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

/**
 * Apply the friendly-editing pass to xlsx bytes (every worksheet with a
 * header row). Returns new xlsx bytes.
 */
export async function beautifyXlsx(bytes: Uint8Array): Promise<Uint8Array> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer);

  for (const ws of wb.worksheets) {
    const headerRow = ws.getRow(1);
    if (headerRow.cellCount === 0) continue;

    const headers: string[] = [];
    headerRow.eachCell({ includeEmpty: false }, (cell, col) => {
      headers[col] = String(cell.value ?? "").trim();
    });
    if (headers.filter(Boolean).length === 0) continue;
    const lastCol = headers.length - 1;

    // 1. Freeze + style the header row.
    ws.views = [{ state: "frozen", ySplit: 1 }];
    headerRow.font = { bold: true };
    headerRow.eachCell({ includeEmpty: false }, (cell) => {
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF3F4F6" }, // light gray
      };
      cell.border = { bottom: { style: "thin", color: { argb: "FFB0B0B0" } } };
    });
    headerRow.height = 20;

    // 2. Autofilter across the header.
    ws.autoFilter = { from: "A1", to: `${colLetter(lastCol)}1` };

    // 3. Widths + per-column behaviour.
    for (let c = 1; c <= lastCol; c++) {
      const label = (headers[c] ?? "").toLowerCase();
      if (!label) continue;
      const column = ws.getColumn(c);
      column.width = WIDTH_BY_HEADER[label] ?? Math.max(14, Math.min(24, label.length + 6));
      if (label === "description") {
        column.alignment = { wrapText: true, vertical: "top" };
      }

      // 4. Dropdowns for enum columns (typed rows well past current data).
      const list = LIST_BY_HEADER[label];
      if (list) {
        const formulae = [`"${list.join(",")}"`];
        for (let r = 2; r <= VALIDATION_ROWS; r++) {
          ws.getCell(`${colLetter(c)}${r}`).dataValidation = {
            type: "list",
            allowBlank: true,
            formulae,
            showErrorMessage: true,
            errorStyle: "warning",
            errorTitle: "Pick from the list",
            error: `Choose one of: ${list.join(", ")} (or leave blank).`,
          };
        }
      }
    }
  }

  const out = await wb.xlsx.writeBuffer();
  return new Uint8Array(out as ArrayBuffer);
}
